name: rick_and_morty_game
description: "Teste técnico para a vaga de Flutter Junior Developer na empresa FTeam"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  bloc_test: ^10.0.0
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
